-- Operational shop schema (mirrors course shop.db) + fraud scoring output.
-- Apply with: supabase db push   (after supabase link)

create table if not exists customers (
  customer_id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null unique,
  gender text not null,
  birthdate timestamptz not null,
  created_at timestamptz not null,
  city text,
  state text,
  zip_code text,
  customer_segment text,
  loyalty_tier text,
  is_active boolean not null default true
);

create table if not exists products (
  product_id bigint generated by default as identity primary key,
  sku text not null unique,
  product_name text not null,
  category text not null,
  price double precision not null,
  cost double precision not null,
  is_active boolean not null default true
);

create table if not exists orders (
  order_id bigint generated by default as identity primary key,
  customer_id bigint not null references customers (customer_id),
  order_datetime timestamptz not null,
  billing_zip text,
  shipping_zip text,
  shipping_state text,
  payment_method text not null,
  device_type text not null,
  ip_country text not null,
  promo_used boolean not null default false,
  promo_code text,
  order_subtotal double precision not null,
  shipping_fee double precision not null,
  tax_amount double precision not null,
  order_total double precision not null,
  risk_score double precision not null,
  is_fraud boolean not null default false
);

create table if not exists order_items (
  order_item_id bigint generated by default as identity primary key,
  order_id bigint not null references orders (order_id) on delete cascade,
  product_id bigint not null references products (product_id),
  quantity integer not null,
  unit_price double precision not null,
  line_total double precision not null
);

create index if not exists idx_order_items_order on order_items (order_id);
create index if not exists idx_order_items_product on order_items (product_id);
create index if not exists idx_orders_customer on orders (customer_id);
create index if not exists idx_orders_datetime on orders (order_datetime);

create table if not exists shipments (
  shipment_id bigint generated by default as identity primary key,
  order_id bigint not null unique references orders (order_id) on delete cascade,
  ship_datetime timestamptz not null,
  carrier text not null,
  shipping_method text not null,
  distance_band text not null,
  promised_days integer not null,
  actual_days integer not null,
  late_delivery boolean not null default false
);

create index if not exists idx_shipments_late on shipments (late_delivery);

create table product_reviews (
  review_id bigint generated by default as identity primary key,
  customer_id bigint not null references customers (customer_id),
  product_id bigint not null references products (product_id),
  rating integer not null check (rating between 1 and 5),
  review_datetime timestamptz not null,
  review_text text,
  unique (customer_id, product_id)
);

create index if not exists idx_reviews_customer on product_reviews (customer_id);
create index if not exists idx_reviews_product on product_reviews (product_id);

create table if not exists order_predictions (
  order_id bigint primary key references orders (order_id) on delete cascade,
  fraud_probability double precision not null,
  predicted_fraud integer not null,
  prediction_timestamp timestamptz not null default now()
);

create or replace view warehouse_priority_rows as
select
  o.order_id,
  o.order_datetime as order_timestamp,
  o.order_total as total_value,
  c.customer_id,
  c.full_name as customer_name,
  p.fraud_probability,
  p.predicted_fraud,
  p.prediction_timestamp
from orders o
join customers c on c.customer_id = o.customer_id
join order_predictions p on p.order_id = o.order_id
where not exists (
  select 1 from shipments s where s.order_id = o.order_id
);

create or replace function place_shop_order (
  p_customer_id bigint,
  p_order_datetime text,
  p_order_subtotal double precision,
  p_order_total double precision,
  p_lines jsonb
) returns bigint
language plpgsql
as $$
declare
  v_order_id bigint;
  elem jsonb;
begin
  insert into orders (
    customer_id,
    order_datetime,
    billing_zip,
    shipping_zip,
    shipping_state,
    payment_method,
    device_type,
    ip_country,
    promo_used,
    promo_code,
    order_subtotal,
    shipping_fee,
    tax_amount,
    order_total,
    risk_score,
    is_fraud
  )
  values (
    p_customer_id,
    p_order_datetime::timestamptz,
    '',
    '',
    '',
    'card',
    'web',
    'US',
    false,
    null,
    p_order_subtotal,
    0,
    0,
    p_order_total,
    0,
    false
  )
  returning order_id into v_order_id;

  for elem in select * from jsonb_array_elements(p_lines)
  loop
    insert into order_items (
      order_id,
      product_id,
      quantity,
      unit_price,
      line_total
    )
    values (
      v_order_id,
      (elem->>'product_id')::bigint,
      (elem->>'quantity')::integer,
      (elem->>'unit_price')::double precision,
      (elem->>'line_total')::double precision
    );
  end loop;

  return v_order_id;
end;
$$;
